repos: 
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - '--args=--config=/home/daniel-wsl/git/Private-Terraform/.tflint.hcl'
      # - id: terraform_checkov
      #   args:
      #     - '--args=--framework terraform'
      #     - '--args=--download-external-modules true'
      #     - '--args=--output cli'
      #     - '--args=--output-file-path=open-checkov-results'
      #     - '--args=--quiet'
      #     - '--args=--compact'
      - id: terraform_docs
        args:
          - '--args=--output-mode=inject'
          - '--args=--lockfile=false'